### ISSUE TITLE
Chapter 01 - Database Introduction

### ISSUE THREAD

**Issue by luke0408** [Poin-Book/2023.09-database#1]
## 세팅
- [x] 참여자 별 Task 작성
- [x] 작성 참여자(Assignees) 등록
- [x] 파일 세팅

## Task 분배
- [x] Item 01 - Introduction : @hamgui-2022 
- [x] Item 02 - View of Data : @hamgui-2022 
- [x] Item 03 - Database Languages : @hamgui-2022 
- [x] Item 04 - Database Design : @luke0408 
- [x] Item 05 - Database Engine : @luke0408 
- [x] Appendix_A - 과제 풀이 : @ShimFFF
