### ISSUE TITLE
Chapter 02 - Introduction to the Relational Model

### ISSUE THREAD

**Issue by luke0408** [Poin-Book/2023.09-database#2]
## 세팅
- [ ] 참여자 별 Task 작성
- [ ] 작성 참여자(Assignees) 등록
- [ ] 파일 세팅

## Task 분배
- [ ] Item 01 - Structure of Relational Databases : @nahy-512 
- [ ] Item 02 - Database Schema : @nahy-512 
- [ ] Item 03 - Keys : @nahy-512 
- [ ] Item 04 - Schema Diagrams : @nahy-512 
- [ ] Item 05 - Relational Query Languages : @nahy-512 
- [ ] Item 06 - The Relational Algebra : @nahy-512 
- [ ] Appendix_A - 과제 풀이 : @hamgui-2022
