### ISSUE TITLE
Chapter 3 - Introduction to SQL

### ISSUE THREAD

**Issue by luke0408** [Poin-Book/2023.09-database#3]
## 세팅
- [x] 참여자 별 Task 작성
- [x] 작성 참여자(Assignees) 등록
- [ ] 파일 세팅

## Task 분배
- [ ] Item 01 - Overview of the SQL Query Language : @nahy-512 
- [ ] Item 02 - SQL Data Definition : @nahy-512 
- [ ] Item 03 - Basic Structure of SQL Queries : @nahy-512  
- [ ] Item 04 - Additional Basic Operations : @luke0408 
- [ ] Item 05 - Set Operations : @luke0408 
- [ ] Item 06 - Aggregate Functions : @luke0408 
- [ ] Item 08 - Nested Subqueries : @luke0408 
- [ ] Item 09 -Modification of the Database : @luke0408 
- [ ] Appendix_A - 과제 풀이 : @hamgui-2022
