### ISSUE TITLE
Chapter 4 - Intermediate SQL

### ISSUE THREAD

**Issue by luke0408** [Poin-Book/2023.09-database#4]
## 세팅
- [ ] 참여자 별 Task 작성
- [ ] 작성 참여자(Assignees) 등록
- [ ] 파일 세팅

## Task 분배
- [ ] Item 01 - Join Expressions
- [ ] Item 02 - Views
- [ ] Item 03 - Transactions
- [ ] Item 04 - Integrity Constraints
- [ ] Item 05 - SQL Data Types and Schemas
- [ ] Appendix_A - Assignment
