### ISSUE TITLE
Chapter 6 - Database Design Using the E-R Model

### ISSUE THREAD

**Issue by luke0408** [Poin-Book/2023.09-database#6]
## 세팅
- [ ] 참여자 별 Task 작성
- [ ] 작성 참여자(Assignees) 등록
- [ ] 파일 세팅

## Task 분배
- [ ] Item 01 - Overview of the Design Process
- [ ] Item 02 - The Entity-Relationship Model
- [ ] Item 03 - Constraints
- [ ] Item 04 - Entity-Relationship Diagrams
- [ ] Appendix_A - Assignment
